# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Build Packages
        run: sudo apt-get install pkg-config build-essential mesa-common-dev libglu1-mesa-dev cmake libxkbcommon-dev libxkbcommon-x11-dev -y

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        
      - name: Install Node Packages
        run: yarn install

      - name: Build Binary
        run: yarn build

      - name: Check for Release File
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: ./deploy/linux/build/KeylightController/Keylight_Controller-x86_64.AppImage
          allow_failure: false

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        
      - name: Install Node Packages
        run: yarn install
      
      - name: Import Code-Signing Certificates
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      
      - name: Pack Sourcecode
        run: yarn webpack

      - name: Build Binary
        run: yarn build

      - name: Sign Binary
        run: 'codesign --deep -fs "Developer ID Application: Justin Forlenza (GWPC475GJ5)" ./deploy/darwin/build/KeylightController.app -v'

      - name: Zip Application
        uses: papeloto/action-zip@v1
        with:
          files: ./deploy/darwin/build/KeylightController.app
          dest: ./deploy/darwin/build/KeylightController.app.zip
      
      - name: Check for Release File
        uses: andstor/file-existence-action@v1.0.1
        with:
          files: ./deploy/darwin/build/KeylightController.app.zip
          allow_failure: false
